// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: tunnel/v1/tunnel.proto

package tunnelpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages sent from the agent to the manager.
type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_HttpResponse
	//	*AgentMessage_HeartbeatPing
	//	*AgentMessage_WsData
	//	*AgentMessage_WsClose
	//	*AgentMessage_StreamData
	//	*AgentMessage_StreamEnd
	//	*AgentMessage_Register
	//	*AgentMessage_Event
	//	*AgentMessage_CommandAck
	//	*AgentMessage_CommandOutput
	//	*AgentMessage_CommandComplete
	//	*AgentMessage_FileChunk
	//	*AgentMessage_StreamClose
	//	*AgentMessage_CancelRequest
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHttpResponse() *HttpResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_HttpResponse); ok {
			return x.HttpResponse
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeatPing() *HeartbeatPing {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_HeartbeatPing); ok {
			return x.HeartbeatPing
		}
	}
	return nil
}

func (x *AgentMessage) GetWsData() *WebSocketData {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_WsData); ok {
			return x.WsData
		}
	}
	return nil
}

func (x *AgentMessage) GetWsClose() *WebSocketClose {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_WsClose); ok {
			return x.WsClose
		}
	}
	return nil
}

func (x *AgentMessage) GetStreamData() *StreamData {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_StreamData); ok {
			return x.StreamData
		}
	}
	return nil
}

func (x *AgentMessage) GetStreamEnd() *StreamEnd {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_StreamEnd); ok {
			return x.StreamEnd
		}
	}
	return nil
}

func (x *AgentMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetEvent() *EventLog {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *AgentMessage) GetCommandAck() *CommandAck {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_CommandAck); ok {
			return x.CommandAck
		}
	}
	return nil
}

func (x *AgentMessage) GetCommandOutput() *CommandOutput {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_CommandOutput); ok {
			return x.CommandOutput
		}
	}
	return nil
}

func (x *AgentMessage) GetCommandComplete() *CommandComplete {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_CommandComplete); ok {
			return x.CommandComplete
		}
	}
	return nil
}

func (x *AgentMessage) GetFileChunk() *FileChunk {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_FileChunk); ok {
			return x.FileChunk
		}
	}
	return nil
}

func (x *AgentMessage) GetStreamClose() *StreamClose {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_StreamClose); ok {
			return x.StreamClose
		}
	}
	return nil
}

func (x *AgentMessage) GetCancelRequest() *CancelRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_CancelRequest); ok {
			return x.CancelRequest
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_HttpResponse struct {
	HttpResponse *HttpResponse `protobuf:"bytes,1,opt,name=http_response,json=httpResponse,proto3,oneof"`
}

type AgentMessage_HeartbeatPing struct {
	HeartbeatPing *HeartbeatPing `protobuf:"bytes,2,opt,name=heartbeat_ping,json=heartbeatPing,proto3,oneof"`
}

type AgentMessage_WsData struct {
	WsData *WebSocketData `protobuf:"bytes,3,opt,name=ws_data,json=wsData,proto3,oneof"`
}

type AgentMessage_WsClose struct {
	WsClose *WebSocketClose `protobuf:"bytes,4,opt,name=ws_close,json=wsClose,proto3,oneof"`
}

type AgentMessage_StreamData struct {
	StreamData *StreamData `protobuf:"bytes,5,opt,name=stream_data,json=streamData,proto3,oneof"`
}

type AgentMessage_StreamEnd struct {
	StreamEnd *StreamEnd `protobuf:"bytes,6,opt,name=stream_end,json=streamEnd,proto3,oneof"`
}

type AgentMessage_Register struct {
	Register *RegisterRequest `protobuf:"bytes,7,opt,name=register,proto3,oneof"`
}

type AgentMessage_Event struct {
	Event *EventLog `protobuf:"bytes,8,opt,name=event,proto3,oneof"`
}

type AgentMessage_CommandAck struct {
	CommandAck *CommandAck `protobuf:"bytes,9,opt,name=command_ack,json=commandAck,proto3,oneof"`
}

type AgentMessage_CommandOutput struct {
	CommandOutput *CommandOutput `protobuf:"bytes,10,opt,name=command_output,json=commandOutput,proto3,oneof"`
}

type AgentMessage_CommandComplete struct {
	CommandComplete *CommandComplete `protobuf:"bytes,11,opt,name=command_complete,json=commandComplete,proto3,oneof"`
}

type AgentMessage_FileChunk struct {
	FileChunk *FileChunk `protobuf:"bytes,12,opt,name=file_chunk,json=fileChunk,proto3,oneof"`
}

type AgentMessage_StreamClose struct {
	StreamClose *StreamClose `protobuf:"bytes,13,opt,name=stream_close,json=streamClose,proto3,oneof"`
}

type AgentMessage_CancelRequest struct {
	// Only sent when the manager advertised the proto-parity-v1 capability;
	// older managers decode an unknown oneof case as a nil payload.
	CancelRequest *CancelRequest `protobuf:"bytes,14,opt,name=cancel_request,json=cancelRequest,proto3,oneof"`
}

func (*AgentMessage_HttpResponse) isAgentMessage_Payload() {}

func (*AgentMessage_HeartbeatPing) isAgentMessage_Payload() {}

func (*AgentMessage_WsData) isAgentMessage_Payload() {}

func (*AgentMessage_WsClose) isAgentMessage_Payload() {}

func (*AgentMessage_StreamData) isAgentMessage_Payload() {}

func (*AgentMessage_StreamEnd) isAgentMessage_Payload() {}

func (*AgentMessage_Register) isAgentMessage_Payload() {}

func (*AgentMessage_Event) isAgentMessage_Payload() {}

func (*AgentMessage_CommandAck) isAgentMessage_Payload() {}

func (*AgentMessage_CommandOutput) isAgentMessage_Payload() {}

func (*AgentMessage_CommandComplete) isAgentMessage_Payload() {}

func (*AgentMessage_FileChunk) isAgentMessage_Payload() {}

func (*AgentMessage_StreamClose) isAgentMessage_Payload() {}

func (*AgentMessage_CancelRequest) isAgentMessage_Payload() {}

// Messages sent from the manager to the agent.
type ManagerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ManagerMessage_HttpRequest
	//	*ManagerMessage_HeartbeatPong
	//	*ManagerMessage_WsStart
	//	*ManagerMessage_WsData
	//	*ManagerMessage_WsClose
	//	*ManagerMessage_RegisterResponse
	//	*ManagerMessage_CommandRequest
	//	*ManagerMessage_StreamOpen
	//	*ManagerMessage_StreamClose
	//	*ManagerMessage_CancelRequest
	//	*ManagerMessage_FileChunk
	//	*ManagerMessage_StreamData
	//	*ManagerMessage_StreamEnd
	//	*ManagerMessage_CommandCredit
	Payload       isManagerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerMessage) Reset() {
	*x = ManagerMessage{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerMessage) ProtoMessage() {}

func (x *ManagerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerMessage.ProtoReflect.Descriptor instead.
func (*ManagerMessage) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *ManagerMessage) GetPayload() isManagerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ManagerMessage) GetHttpRequest() *HttpRequest {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_HttpRequest); ok {
			return x.HttpRequest
		}
	}
	return nil
}

func (x *ManagerMessage) GetHeartbeatPong() *HeartbeatPong {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_HeartbeatPong); ok {
			return x.HeartbeatPong
		}
	}
	return nil
}

func (x *ManagerMessage) GetWsStart() *WebSocketStart {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_WsStart); ok {
			return x.WsStart
		}
	}
	return nil
}

func (x *ManagerMessage) GetWsData() *WebSocketData {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_WsData); ok {
			return x.WsData
		}
	}
	return nil
}

func (x *ManagerMessage) GetWsClose() *WebSocketClose {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_WsClose); ok {
			return x.WsClose
		}
	}
	return nil
}

func (x *ManagerMessage) GetRegisterResponse() *RegisterResponse {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_RegisterResponse); ok {
			return x.RegisterResponse
		}
	}
	return nil
}

func (x *ManagerMessage) GetCommandRequest() *CommandRequest {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_CommandRequest); ok {
			return x.CommandRequest
		}
	}
	return nil
}

func (x *ManagerMessage) GetStreamOpen() *StreamOpen {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_StreamOpen); ok {
			return x.StreamOpen
		}
	}
	return nil
}

func (x *ManagerMessage) GetStreamClose() *StreamClose {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_StreamClose); ok {
			return x.StreamClose
		}
	}
	return nil
}

func (x *ManagerMessage) GetCancelRequest() *CancelRequest {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_CancelRequest); ok {
			return x.CancelRequest
		}
	}
	return nil
}

func (x *ManagerMessage) GetFileChunk() *FileChunk {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_FileChunk); ok {
			return x.FileChunk
		}
	}
	return nil
}

func (x *ManagerMessage) GetStreamData() *StreamData {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_StreamData); ok {
			return x.StreamData
		}
	}
	return nil
}

func (x *ManagerMessage) GetStreamEnd() *StreamEnd {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_StreamEnd); ok {
			return x.StreamEnd
		}
	}
	return nil
}

func (x *ManagerMessage) GetCommandCredit() *CommandCredit {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_CommandCredit); ok {
			return x.CommandCredit
		}
	}
	return nil
}

type isManagerMessage_Payload interface {
	isManagerMessage_Payload()
}

type ManagerMessage_HttpRequest struct {
	HttpRequest *HttpRequest `protobuf:"bytes,1,opt,name=http_request,json=httpRequest,proto3,oneof"`
}

type ManagerMessage_HeartbeatPong struct {
	HeartbeatPong *HeartbeatPong `protobuf:"bytes,2,opt,name=heartbeat_pong,json=heartbeatPong,proto3,oneof"`
}

type ManagerMessage_WsStart struct {
	WsStart *WebSocketStart `protobuf:"bytes,3,opt,name=ws_start,json=wsStart,proto3,oneof"`
}

type ManagerMessage_WsData struct {
	WsData *WebSocketData `protobuf:"bytes,4,opt,name=ws_data,json=wsData,proto3,oneof"`
}

type ManagerMessage_WsClose struct {
	WsClose *WebSocketClose `protobuf:"bytes,5,opt,name=ws_close,json=wsClose,proto3,oneof"`
}

type ManagerMessage_RegisterResponse struct {
	RegisterResponse *RegisterResponse `protobuf:"bytes,6,opt,name=register_response,json=registerResponse,proto3,oneof"`
}

type ManagerMessage_CommandRequest struct {
	CommandRequest *CommandRequest `protobuf:"bytes,7,opt,name=command_request,json=commandRequest,proto3,oneof"`
}

type ManagerMessage_StreamOpen struct {
	StreamOpen *StreamOpen `protobuf:"bytes,8,opt,name=stream_open,json=streamOpen,proto3,oneof"`
}

type ManagerMessage_StreamClose struct {
	StreamClose *StreamClose `protobuf:"bytes,9,opt,name=stream_close,json=streamClose,proto3,oneof"`
}

type ManagerMessage_CancelRequest struct {
	CancelRequest *CancelRequest `protobuf:"bytes,10,opt,name=cancel_request,json=cancelRequest,proto3,oneof"`
}

type ManagerMessage_FileChunk struct {
	FileChunk *FileChunk `protobuf:"bytes,11,opt,name=file_chunk,json=fileChunk,proto3,oneof"`
}

type ManagerMessage_StreamData struct {
	// Only sent when the agent advertised the proto-parity-v1 capability;
	// older agents decode an unknown oneof case as a nil payload.
	StreamData *StreamData `protobuf:"bytes,12,opt,name=stream_data,json=streamData,proto3,oneof"`
}

type ManagerMessage_StreamEnd struct {
	StreamEnd *StreamEnd `protobuf:"bytes,13,opt,name=stream_end,json=streamEnd,proto3,oneof"`
}

type ManagerMessage_CommandCredit struct {
	// Only sent to agents that advertised command-credit-v1.
	CommandCredit *CommandCredit `protobuf:"bytes,14,opt,name=command_credit,json=commandCredit,proto3,oneof"`
}

func (*ManagerMessage_HttpRequest) isManagerMessage_Payload() {}

func (*ManagerMessage_HeartbeatPong) isManagerMessage_Payload() {}

func (*ManagerMessage_WsStart) isManagerMessage_Payload() {}

func (*ManagerMessage_WsData) isManagerMessage_Payload() {}

func (*ManagerMessage_WsClose) isManagerMessage_Payload() {}

func (*ManagerMessage_RegisterResponse) isManagerMessage_Payload() {}

func (*ManagerMessage_CommandRequest) isManagerMessage_Payload() {}

func (*ManagerMessage_StreamOpen) isManagerMessage_Payload() {}

func (*ManagerMessage_StreamClose) isManagerMessage_Payload() {}

func (*ManagerMessage_CancelRequest) isManagerMessage_Payload() {}

func (*ManagerMessage_FileChunk) isManagerMessage_Payload() {}

func (*ManagerMessage_StreamData) isManagerMessage_Payload() {}

func (*ManagerMessage_StreamEnd) isManagerMessage_Payload() {}

func (*ManagerMessage_CommandCredit) isManagerMessage_Payload() {}

type RegisterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentToken      string                 `protobuf:"bytes,1,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	AgentInstanceId string                 `protobuf:"bytes,2,opt,name=agent_instance_id,json=agentInstanceId,proto3" json:"agent_instance_id,omitempty"`
	Capabilities    []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	ResumeSessionId string                 `protobuf:"bytes,4,opt,name=resume_session_id,json=resumeSessionId,proto3" json:"resume_session_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

func (x *RegisterRequest) GetAgentInstanceId() string {
	if x != nil {
		return x.AgentInstanceId
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterRequest) GetResumeSessionId() string {
	if x != nil {
		return x.ResumeSessionId
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	EnvironmentId string                 `protobuf:"bytes,2,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SecurityMode  string                 `protobuf:"bytes,5,opt,name=security_mode,json=securityMode,proto3" json:"security_mode,omitempty"`
	Capabilities  []string               `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	DrainPrevious bool                   `protobuf:"varint,7,opt,name=drain_previous,json=drainPrevious,proto3" json:"drain_previous,omitempty"`
	Id            string                 `protobuf:"bytes,8,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *RegisterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RegisterResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterResponse) GetSecurityMode() string {
	if x != nil {
		return x.SecurityMode
	}
	return ""
}

func (x *RegisterResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterResponse) GetDrainPrevious() bool {
	if x != nil {
		return x.DrainPrevious
	}
	return false
}

func (x *RegisterResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CommandRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CommandId       string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	CommandName     string                 `protobuf:"bytes,2,opt,name=command_name,json=commandName,proto3" json:"command_name,omitempty"`
	Method          string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Path            string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Query           string                 `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	Headers         map[string]string      `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body            []byte                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	TimeoutMillis   int64                  `protobuf:"varint,8,opt,name=timeout_millis,json=timeoutMillis,proto3" json:"timeout_millis,omitempty"`
	SessionId       string                 `protobuf:"bytes,9,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentInstanceId string                 `protobuf:"bytes,10,opt,name=agent_instance_id,json=agentInstanceId,proto3" json:"agent_instance_id,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *CommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandRequest) GetCommandName() string {
	if x != nil {
		return x.CommandName
	}
	return ""
}

func (x *CommandRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CommandRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CommandRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *CommandRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CommandRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *CommandRequest) GetTimeoutMillis() int64 {
	if x != nil {
		return x.TimeoutMillis
	}
	return 0
}

func (x *CommandRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CommandRequest) GetAgentInstanceId() string {
	if x != nil {
		return x.AgentInstanceId
	}
	return ""
}

func (x *CommandRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CommandAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAck) Reset() {
	*x = CommandAck{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAck) ProtoMessage() {}

func (x *CommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAck.ProtoReflect.Descriptor instead.
func (*CommandAck) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{5}
}

func (x *CommandAck) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type CommandOutput struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Data      []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Sequence  int64                  `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Set on the first chunk so the manager can stream the response before
	// command_complete arrives. Older managers ignore these fields.
	Status        int32             `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Headers       map[string]string `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandOutput) Reset() {
	*x = CommandOutput{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandOutput) ProtoMessage() {}

func (x *CommandOutput) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandOutput.ProtoReflect.Descriptor instead.
func (*CommandOutput) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{6}
}

func (x *CommandOutput) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CommandOutput) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *CommandOutput) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CommandOutput) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type CommandComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Streaming     bool                   `protobuf:"varint,6,opt,name=streaming,proto3" json:"streaming,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandComplete) Reset() {
	*x = CommandComplete{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandComplete) ProtoMessage() {}

func (x *CommandComplete) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandComplete.ProtoReflect.Descriptor instead.
func (*CommandComplete) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{7}
}

func (x *CommandComplete) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandComplete) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CommandComplete) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CommandComplete) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *CommandComplete) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandComplete) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Sequence      int64                  `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Eof           bool                   `protobuf:"varint,4,opt,name=eof,proto3" json:"eof,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{8}
}

func (x *FileChunk) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileChunk) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *FileChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

func (x *FileChunk) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type StreamOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	CommandName   string                 `protobuf:"bytes,2,opt,name=command_name,json=commandName,proto3" json:"command_name,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Query         string                 `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SessionId     string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOpen) Reset() {
	*x = StreamOpen{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOpen) ProtoMessage() {}

func (x *StreamOpen) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOpen.ProtoReflect.Descriptor instead.
func (*StreamOpen) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{9}
}

func (x *StreamOpen) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *StreamOpen) GetCommandName() string {
	if x != nil {
		return x.CommandName
	}
	return ""
}

func (x *StreamOpen) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StreamOpen) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *StreamOpen) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *StreamOpen) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StreamClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamClose) Reset() {
	*x = StreamClose{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamClose) ProtoMessage() {}

func (x *StreamClose) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamClose.ProtoReflect.Descriptor instead.
func (*StreamClose) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{10}
}

func (x *StreamClose) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *StreamClose) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{11}
}

func (x *CancelRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

// CommandCredit returns flow-control credit for command output the manager has consumed.
type CommandCredit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Bytes         int64                  `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandCredit) Reset() {
	*x = CommandCredit{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandCredit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandCredit) ProtoMessage() {}

func (x *CommandCredit) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandCredit.ProtoReflect.Descriptor instead.
func (*CommandCredit) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{12}
}

func (x *CommandCredit) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandCredit) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

type HttpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Query         string                 `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRequest) Reset() {
	*x = HttpRequest{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequest) ProtoMessage() {}

func (x *HttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequest.ProtoReflect.Descriptor instead.
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{13}
}

func (x *HttpRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *HttpRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type HttpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpResponse) Reset() {
	*x = HttpResponse{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponse) ProtoMessage() {}

func (x *HttpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponse.ProtoReflect.Descriptor instead.
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{14}
}

func (x *HttpResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HttpResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HttpResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// StreamData carries incremental HTTP response body chunks.
type StreamData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	MessageType   int32                  `protobuf:"varint,3,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamData) Reset() {
	*x = StreamData{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamData) ProtoMessage() {}

func (x *StreamData) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamData.ProtoReflect.Descriptor instead.
func (*StreamData) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{15}
}

func (x *StreamData) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StreamData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StreamData) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

type StreamEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEnd) Reset() {
	*x = StreamEnd{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEnd) ProtoMessage() {}

func (x *StreamEnd) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEnd.ProtoReflect.Descriptor instead.
func (*StreamEnd) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{16}
}

func (x *StreamEnd) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type HeartbeatPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatPing) Reset() {
	*x = HeartbeatPing{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPing) ProtoMessage() {}

func (x *HeartbeatPing) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPing.ProtoReflect.Descriptor instead.
func (*HeartbeatPing) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{17}
}

func (x *HeartbeatPing) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type HeartbeatPong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatPong) Reset() {
	*x = HeartbeatPong{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPong) ProtoMessage() {}

func (x *HeartbeatPong) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPong.ProtoReflect.Descriptor instead.
func (*HeartbeatPong) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{18}
}

func (x *HeartbeatPong) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WebSocketStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketStart) Reset() {
	*x = WebSocketStart{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketStart) ProtoMessage() {}

func (x *WebSocketStart) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketStart.ProtoReflect.Descriptor instead.
func (*WebSocketStart) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{19}
}

func (x *WebSocketStart) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *WebSocketStart) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WebSocketStart) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *WebSocketStart) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type WebSocketData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	MessageType   int32                  `protobuf:"varint,3,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketData) Reset() {
	*x = WebSocketData{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketData) ProtoMessage() {}

func (x *WebSocketData) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketData.ProtoReflect.Descriptor instead.
func (*WebSocketData) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{20}
}

func (x *WebSocketData) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *WebSocketData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WebSocketData) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

type WebSocketClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketClose) Reset() {
	*x = WebSocketClose{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketClose) ProtoMessage() {}

func (x *WebSocketClose) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketClose.ProtoReflect.Descriptor instead.
func (*WebSocketClose) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{21}
}

func (x *WebSocketClose) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

// EventLog carries an event emitted on an agent and synced to manager.
type EventLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ResourceType  string                 `protobuf:"bytes,5,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId    string                 `protobuf:"bytes,6,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceName  string                 `protobuf:"bytes,7,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	UserId        string                 `protobuf:"bytes,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,9,opt,name=username,proto3" json:"username,omitempty"`
	MetadataJson  []byte                 `protobuf:"bytes,10,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	Id            string                 `protobuf:"bytes,11,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventLog) Reset() {
	*x = EventLog{}
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventLog) ProtoMessage() {}

func (x *EventLog) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_v1_tunnel_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventLog.ProtoReflect.Descriptor instead.
func (*EventLog) Descriptor() ([]byte, []int) {
	return file_tunnel_v1_tunnel_proto_rawDescGZIP(), []int{22}
}

func (x *EventLog) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventLog) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *EventLog) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EventLog) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EventLog) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *EventLog) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *EventLog) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *EventLog) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EventLog) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *EventLog) GetMetadataJson() []byte {
	if x != nil {
		return x.MetadataJson
	}
	return nil
}

func (x *EventLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_tunnel_v1_tunnel_proto protoreflect.FileDescriptor

const file_tunnel_v1_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x16tunnel/v1/tunnel.proto\x12\ttunnel.v1\"\xde\x06\n" +
	"\fAgentMessage\x12>\n" +
	"\rhttp_response\x18\x01 \x01(\v2\x17.tunnel.v1.HttpResponseH\x00R\fhttpResponse\x12A\n" +
	"\x0eheartbeat_ping\x18\x02 \x01(\v2\x18.tunnel.v1.HeartbeatPingH\x00R\rheartbeatPing\x123\n" +
	"\aws_data\x18\x03 \x01(\v2\x18.tunnel.v1.WebSocketDataH\x00R\x06wsData\x126\n" +
	"\bws_close\x18\x04 \x01(\v2\x19.tunnel.v1.WebSocketCloseH\x00R\awsClose\x128\n" +
	"\vstream_data\x18\x05 \x01(\v2\x15.tunnel.v1.StreamDataH\x00R\n" +
	"streamData\x125\n" +
	"\n" +
	"stream_end\x18\x06 \x01(\v2\x14.tunnel.v1.StreamEndH\x00R\tstreamEnd\x128\n" +
	"\bregister\x18\a \x01(\v2\x1a.tunnel.v1.RegisterRequestH\x00R\bregister\x12+\n" +
	"\x05event\x18\b \x01(\v2\x13.tunnel.v1.EventLogH\x00R\x05event\x128\n" +
	"\vcommand_ack\x18\t \x01(\v2\x15.tunnel.v1.CommandAckH\x00R\n" +
	"commandAck\x12A\n" +
	"\x0ecommand_output\x18\n" +
	" \x01(\v2\x18.tunnel.v1.CommandOutputH\x00R\rcommandOutput\x12G\n" +
	"\x10command_complete\x18\v \x01(\v2\x1a.tunnel.v1.CommandCompleteH\x00R\x0fcommandComplete\x125\n" +
	"\n" +
	"file_chunk\x18\f \x01(\v2\x14.tunnel.v1.FileChunkH\x00R\tfileChunk\x12;\n" +
	"\fstream_close\x18\r \x01(\v2\x16.tunnel.v1.StreamCloseH\x00R\vstreamClose\x12A\n" +
	"\x0ecancel_request\x18\x0e \x01(\v2\x18.tunnel.v1.CancelRequestH\x00R\rcancelRequestB\t\n" +
	"\apayload\"\xf7\x06\n" +
	"\x0eManagerMessage\x12;\n" +
	"\fhttp_request\x18\x01 \x01(\v2\x16.tunnel.v1.HttpRequestH\x00R\vhttpRequest\x12A\n" +
	"\x0eheartbeat_pong\x18\x02 \x01(\v2\x18.tunnel.v1.HeartbeatPongH\x00R\rheartbeatPong\x126\n" +
	"\bws_start\x18\x03 \x01(\v2\x19.tunnel.v1.WebSocketStartH\x00R\awsStart\x123\n" +
	"\aws_data\x18\x04 \x01(\v2\x18.tunnel.v1.WebSocketDataH\x00R\x06wsData\x126\n" +
	"\bws_close\x18\x05 \x01(\v2\x19.tunnel.v1.WebSocketCloseH\x00R\awsClose\x12J\n" +
	"\x11register_response\x18\x06 \x01(\v2\x1b.tunnel.v1.RegisterResponseH\x00R\x10registerResponse\x12D\n" +
	"\x0fcommand_request\x18\a \x01(\v2\x19.tunnel.v1.CommandRequestH\x00R\x0ecommandRequest\x128\n" +
	"\vstream_open\x18\b \x01(\v2\x15.tunnel.v1.StreamOpenH\x00R\n" +
	"streamOpen\x12;\n" +
	"\fstream_close\x18\t \x01(\v2\x16.tunnel.v1.StreamCloseH\x00R\vstreamClose\x12A\n" +
	"\x0ecancel_request\x18\n" +
	" \x01(\v2\x18.tunnel.v1.CancelRequestH\x00R\rcancelRequest\x125\n" +
	"\n" +
	"file_chunk\x18\v \x01(\v2\x14.tunnel.v1.FileChunkH\x00R\tfileChunk\x128\n" +
	"\vstream_data\x18\f \x01(\v2\x15.tunnel.v1.StreamDataH\x00R\n" +
	"streamData\x125\n" +
	"\n" +
	"stream_end\x18\r \x01(\v2\x14.tunnel.v1.StreamEndH\x00R\tstreamEnd\x12A\n" +
	"\x0ecommand_credit\x18\x0e \x01(\v2\x18.tunnel.v1.CommandCreditH\x00R\rcommandCreditB\t\n" +
	"\apayload\"\xae\x01\n" +
	"\x0fRegisterRequest\x12\x1f\n" +
	"\vagent_token\x18\x01 \x01(\tR\n" +
	"agentToken\x12*\n" +
	"\x11agent_instance_id\x18\x02 \x01(\tR\x0fagentInstanceId\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12*\n" +
	"\x11resume_session_id\x18\x04 \x01(\tR\x0fresumeSessionId\"\x8a\x02\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12%\n" +
	"\x0eenvironment_id\x18\x02 \x01(\tR\renvironmentId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12#\n" +
	"\rsecurity_mode\x18\x05 \x01(\tR\fsecurityMode\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\x12%\n" +
	"\x0edrain_previous\x18\a \x01(\bR\rdrainPrevious\x12\x0e\n" +
	"\x02id\x18\b \x01(\tR\x02id\"\x9a\x04\n" +
	"\x0eCommandRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12!\n" +
	"\fcommand_name\x18\x02 \x01(\tR\vcommandName\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\x05 \x01(\tR\x05query\x12@\n" +
	"\aheaders\x18\x06 \x03(\v2&.tunnel.v1.CommandRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\a \x01(\fR\x04body\x12%\n" +
	"\x0etimeout_millis\x18\b \x01(\x03R\rtimeoutMillis\x12\x1d\n" +
	"\n" +
	"session_id\x18\t \x01(\tR\tsessionId\x12*\n" +
	"\x11agent_instance_id\x18\n" +
	" \x01(\tR\x0fagentInstanceId\x12C\n" +
	"\bmetadata\x18\v \x03(\v2'.tunnel.v1.CommandRequest.MetadataEntryR\bmetadata\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"+\n" +
	"\n" +
	"CommandAck\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\"\xf3\x01\n" +
	"\rCommandOutput\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x03R\bsequence\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12?\n" +
	"\aheaders\x18\x05 \x03(\v2%.tunnel.v1.CommandOutput.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x02\n" +
	"\x0fCommandComplete\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12A\n" +
	"\aheaders\x18\x03 \x03(\v2'.tunnel.v1.CommandComplete.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1c\n" +
	"\tstreaming\x18\x06 \x01(\bR\tstreaming\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xeb\x01\n" +
	"\tFileChunk\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x03R\bsequence\x12\x10\n" +
	"\x03eof\x18\x04 \x01(\bR\x03eof\x12>\n" +
	"\bmetadata\x18\x05 \x03(\v2\".tunnel.v1.FileChunk.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x02\n" +
	"\n" +
	"StreamOpen\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12!\n" +
	"\fcommand_name\x18\x02 \x01(\tR\vcommandName\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\x04 \x01(\tR\x05query\x12<\n" +
	"\aheaders\x18\x05 \x03(\v2\".tunnel.v1.StreamOpen.HeadersEntryR\aheaders\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\vStreamClose\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\".\n" +
	"\rCancelRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\"D\n" +
	"\rCommandCredit\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x14\n" +
	"\x05bytes\x18\x02 \x01(\x03R\x05bytes\"\xfd\x01\n" +
	"\vHttpRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\x04 \x01(\tR\x05query\x12=\n" +
	"\aheaders\x18\x05 \x03(\v2#.tunnel.v1.HttpRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd5\x01\n" +
	"\fHttpResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12>\n" +
	"\aheaders\x18\x03 \x03(\v2$.tunnel.v1.HttpResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"b\n" +
	"\n" +
	"StreamData\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12!\n" +
	"\fmessage_type\x18\x03 \x01(\x05R\vmessageType\"*\n" +
	"\tStreamEnd\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\x1f\n" +
	"\rHeartbeatPing\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1f\n" +
	"\rHeartbeatPong\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xd5\x01\n" +
	"\x0eWebSocketStart\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12@\n" +
	"\aheaders\x18\x04 \x03(\v2&.tunnel.v1.WebSocketStart.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"c\n" +
	"\rWebSocketData\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12!\n" +
	"\fmessage_type\x18\x03 \x01(\x05R\vmessageType\"-\n" +
	"\x0eWebSocketClose\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\"\xc7\x02\n" +
	"\bEventLog\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\rresource_type\x18\x05 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x06 \x01(\tR\n" +
	"resourceId\x12#\n" +
	"\rresource_name\x18\a \x01(\tR\fresourceName\x12\x17\n" +
	"\auser_id\x18\b \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\t \x01(\tR\busername\x12#\n" +
	"\rmetadata_json\x18\n" +
	" \x01(\fR\fmetadataJson\x12\x0e\n" +
	"\x02id\x18\v \x01(\tR\x02id2R\n" +
	"\rTunnelService\x12A\n" +
	"\aConnect\x12\x17.tunnel.v1.AgentMessage\x1a\x19.tunnel.v1.ManagerMessage(\x010\x01BDZBgithub.com/getarcaneapp/arcane/backend/v2/proto/tunnel/v1;tunnelpbb\x06proto3"

var (
	file_tunnel_v1_tunnel_proto_rawDescOnce sync.Once
	file_tunnel_v1_tunnel_proto_rawDescData []byte
)

func file_tunnel_v1_tunnel_proto_rawDescGZIP() []byte {
	file_tunnel_v1_tunnel_proto_rawDescOnce.Do(func() {
		file_tunnel_v1_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tunnel_v1_tunnel_proto_rawDesc), len(file_tunnel_v1_tunnel_proto_rawDesc)))
	})
	return file_tunnel_v1_tunnel_proto_rawDescData
}

var file_tunnel_v1_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_tunnel_v1_tunnel_proto_goTypes = []any{
	(*AgentMessage)(nil),     // 0: tunnel.v1.AgentMessage
	(*ManagerMessage)(nil),   // 1: tunnel.v1.ManagerMessage
	(*RegisterRequest)(nil),  // 2: tunnel.v1.RegisterRequest
	(*RegisterResponse)(nil), // 3: tunnel.v1.RegisterResponse
	(*CommandRequest)(nil),   // 4: tunnel.v1.CommandRequest
	(*CommandAck)(nil),       // 5: tunnel.v1.CommandAck
	(*CommandOutput)(nil),    // 6: tunnel.v1.CommandOutput
	(*CommandComplete)(nil),  // 7: tunnel.v1.CommandComplete
	(*FileChunk)(nil),        // 8: tunnel.v1.FileChunk
	(*StreamOpen)(nil),       // 9: tunnel.v1.StreamOpen
	(*StreamClose)(nil),      // 10: tunnel.v1.StreamClose
	(*CancelRequest)(nil),    // 11: tunnel.v1.CancelRequest
	(*CommandCredit)(nil),    // 12: tunnel.v1.CommandCredit
	(*HttpRequest)(nil),      // 13: tunnel.v1.HttpRequest
	(*HttpResponse)(nil),     // 14: tunnel.v1.HttpResponse
	(*StreamData)(nil),       // 15: tunnel.v1.StreamData
	(*StreamEnd)(nil),        // 16: tunnel.v1.StreamEnd
	(*HeartbeatPing)(nil),    // 17: tunnel.v1.HeartbeatPing
	(*HeartbeatPong)(nil),    // 18: tunnel.v1.HeartbeatPong
	(*WebSocketStart)(nil),   // 19: tunnel.v1.WebSocketStart
	(*WebSocketData)(nil),    // 20: tunnel.v1.WebSocketData
	(*WebSocketClose)(nil),   // 21: tunnel.v1.WebSocketClose
	(*EventLog)(nil),         // 22: tunnel.v1.EventLog
	nil,                      // 23: tunnel.v1.CommandRequest.HeadersEntry
	nil,                      // 24: tunnel.v1.CommandRequest.MetadataEntry
	nil,                      // 25: tunnel.v1.CommandOutput.HeadersEntry
	nil,                      // 26: tunnel.v1.CommandComplete.HeadersEntry
	nil,                      // 27: tunnel.v1.FileChunk.MetadataEntry
	nil,                      // 28: tunnel.v1.StreamOpen.HeadersEntry
	nil,                      // 29: tunnel.v1.HttpRequest.HeadersEntry
	nil,                      // 30: tunnel.v1.HttpResponse.HeadersEntry
	nil,                      // 31: tunnel.v1.WebSocketStart.HeadersEntry
}
var file_tunnel_v1_tunnel_proto_depIdxs = []int32{
	14, // 0: tunnel.v1.AgentMessage.http_response:type_name -> tunnel.v1.HttpResponse
	17, // 1: tunnel.v1.AgentMessage.heartbeat_ping:type_name -> tunnel.v1.HeartbeatPing
	20, // 2: tunnel.v1.AgentMessage.ws_data:type_name -> tunnel.v1.WebSocketData
	21, // 3: tunnel.v1.AgentMessage.ws_close:type_name -> tunnel.v1.WebSocketClose
	15, // 4: tunnel.v1.AgentMessage.stream_data:type_name -> tunnel.v1.StreamData
	16, // 5: tunnel.v1.AgentMessage.stream_end:type_name -> tunnel.v1.StreamEnd
	2,  // 6: tunnel.v1.AgentMessage.register:type_name -> tunnel.v1.RegisterRequest
	22, // 7: tunnel.v1.AgentMessage.event:type_name -> tunnel.v1.EventLog
	5,  // 8: tunnel.v1.AgentMessage.command_ack:type_name -> tunnel.v1.CommandAck
	6,  // 9: tunnel.v1.AgentMessage.command_output:type_name -> tunnel.v1.CommandOutput
	7,  // 10: tunnel.v1.AgentMessage.command_complete:type_name -> tunnel.v1.CommandComplete
	8,  // 11: tunnel.v1.AgentMessage.file_chunk:type_name -> tunnel.v1.FileChunk
	10, // 12: tunnel.v1.AgentMessage.stream_close:type_name -> tunnel.v1.StreamClose
	11, // 13: tunnel.v1.AgentMessage.cancel_request:type_name -> tunnel.v1.CancelRequest
	13, // 14: tunnel.v1.ManagerMessage.http_request:type_name -> tunnel.v1.HttpRequest
	18, // 15: tunnel.v1.ManagerMessage.heartbeat_pong:type_name -> tunnel.v1.HeartbeatPong
	19, // 16: tunnel.v1.ManagerMessage.ws_start:type_name -> tunnel.v1.WebSocketStart
	20, // 17: tunnel.v1.ManagerMessage.ws_data:type_name -> tunnel.v1.WebSocketData
	21, // 18: tunnel.v1.ManagerMessage.ws_close:type_name -> tunnel.v1.WebSocketClose
	3,  // 19: tunnel.v1.ManagerMessage.register_response:type_name -> tunnel.v1.RegisterResponse
	4,  // 20: tunnel.v1.ManagerMessage.command_request:type_name -> tunnel.v1.CommandRequest
	9,  // 21: tunnel.v1.ManagerMessage.stream_open:type_name -> tunnel.v1.StreamOpen
	10, // 22: tunnel.v1.ManagerMessage.stream_close:type_name -> tunnel.v1.StreamClose
	11, // 23: tunnel.v1.ManagerMessage.cancel_request:type_name -> tunnel.v1.CancelRequest
	8,  // 24: tunnel.v1.ManagerMessage.file_chunk:type_name -> tunnel.v1.FileChunk
	15, // 25: tunnel.v1.ManagerMessage.stream_data:type_name -> tunnel.v1.StreamData
	16, // 26: tunnel.v1.ManagerMessage.stream_end:type_name -> tunnel.v1.StreamEnd
	12, // 27: tunnel.v1.ManagerMessage.command_credit:type_name -> tunnel.v1.CommandCredit
	23, // 28: tunnel.v1.CommandRequest.headers:type_name -> tunnel.v1.CommandRequest.HeadersEntry
	24, // 29: tunnel.v1.CommandRequest.metadata:type_name -> tunnel.v1.CommandRequest.MetadataEntry
	25, // 30: tunnel.v1.CommandOutput.headers:type_name -> tunnel.v1.CommandOutput.HeadersEntry
	26, // 31: tunnel.v1.CommandComplete.headers:type_name -> tunnel.v1.CommandComplete.HeadersEntry
	27, // 32: tunnel.v1.FileChunk.metadata:type_name -> tunnel.v1.FileChunk.MetadataEntry
	28, // 33: tunnel.v1.StreamOpen.headers:type_name -> tunnel.v1.StreamOpen.HeadersEntry
	29, // 34: tunnel.v1.HttpRequest.headers:type_name -> tunnel.v1.HttpRequest.HeadersEntry
	30, // 35: tunnel.v1.HttpResponse.headers:type_name -> tunnel.v1.HttpResponse.HeadersEntry
	31, // 36: tunnel.v1.WebSocketStart.headers:type_name -> tunnel.v1.WebSocketStart.HeadersEntry
	0,  // 37: tunnel.v1.TunnelService.Connect:input_type -> tunnel.v1.AgentMessage
	1,  // 38: tunnel.v1.TunnelService.Connect:output_type -> tunnel.v1.ManagerMessage
	38, // [38:39] is the sub-list for method output_type
	37, // [37:38] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_tunnel_v1_tunnel_proto_init() }
func file_tunnel_v1_tunnel_proto_init() {
	if File_tunnel_v1_tunnel_proto != nil {
		return
	}
	file_tunnel_v1_tunnel_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_HttpResponse)(nil),
		(*AgentMessage_HeartbeatPing)(nil),
		(*AgentMessage_WsData)(nil),
		(*AgentMessage_WsClose)(nil),
		(*AgentMessage_StreamData)(nil),
		(*AgentMessage_StreamEnd)(nil),
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Event)(nil),
		(*AgentMessage_CommandAck)(nil),
		(*AgentMessage_CommandOutput)(nil),
		(*AgentMessage_CommandComplete)(nil),
		(*AgentMessage_FileChunk)(nil),
		(*AgentMessage_StreamClose)(nil),
		(*AgentMessage_CancelRequest)(nil),
	}
	file_tunnel_v1_tunnel_proto_msgTypes[1].OneofWrappers = []any{
		(*ManagerMessage_HttpRequest)(nil),
		(*ManagerMessage_HeartbeatPong)(nil),
		(*ManagerMessage_WsStart)(nil),
		(*ManagerMessage_WsData)(nil),
		(*ManagerMessage_WsClose)(nil),
		(*ManagerMessage_RegisterResponse)(nil),
		(*ManagerMessage_CommandRequest)(nil),
		(*ManagerMessage_StreamOpen)(nil),
		(*ManagerMessage_StreamClose)(nil),
		(*ManagerMessage_CancelRequest)(nil),
		(*ManagerMessage_FileChunk)(nil),
		(*ManagerMessage_StreamData)(nil),
		(*ManagerMessage_StreamEnd)(nil),
		(*ManagerMessage_CommandCredit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tunnel_v1_tunnel_proto_rawDesc), len(file_tunnel_v1_tunnel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tunnel_v1_tunnel_proto_goTypes,
		DependencyIndexes: file_tunnel_v1_tunnel_proto_depIdxs,
		MessageInfos:      file_tunnel_v1_tunnel_proto_msgTypes,
	}.Build()
	File_tunnel_v1_tunnel_proto = out.File
	file_tunnel_v1_tunnel_proto_goTypes = nil
	file_tunnel_v1_tunnel_proto_depIdxs = nil
}
